title: CHAYEOI
email: y2oniary@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CHAYEOI 기술 블로그
permalink: '/learn/:categories/:title/' # default '/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chayeoi.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Chanyeon Kim # add your name
author-pic: chayeoi-profile.jpg
about-author: 자바스크립트를 무척 좋아하는 주니어 프론트엔드 개발자입니다. 현재 React.js, Vue.js, Node.js를 공부 중에 있습니다.

# Contact links
email: y2oniary@gmail.com # Add your Email address
phone: 010-2650-5090 # Add your Phone number
website: chayeoi.creatorlink.net # Add your website, do not add http://
repo: y2oniary
# linkedin: # Add your Linkedin handle
github: chayeoi # Add your Github handle
# twitter: '@artemsheludko_' # Add your Twitter handle
facebook: chayeoi # Add your Facebook handle
instagram: chayeoi # Add your Instagram handle
# pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
disqus_identifier: y2oniary # Add your discus identifier

# Tracker
analytics: # Google Analytics

# # Paginate
# paginate: 6
# paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
